plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.fongmi.hook'

    compileSdk 35

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation libs.annotation
    coreLibraryDesugaring libs.desugar
}