plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.ghost.thunder'

    compileSdk 35

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
}

dependencies {
    implementation project(':catvod')
    coreLibraryDesugaring libs.desugar
}