plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.fongmi.android.tv.quickjs'

    compileSdk 35

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    lint {
        disable 'UnsafeOptInUsageError'
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar
    implementation project(':catvod')
    implementation 'wang.harlon.quickjs:wrapper-java:3.2.0'
    implementation 'wang.harlon.quickjs:wrapper-android:3.2.0'
    implementation 'net.sourceforge.streamsupport:android-retrofuture:1.7.4'
}